sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSUbNq9xAvwrT6FCAxq
    access-key-secret: wabU56wSGfZQbv1TwCcQzdmOeiJvYF
    bucket-name: web-lzbo
